# Generated by Django 3.1 on 2020-09-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('emailAddress', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ContactUs',
            },
        ),
    ]
